-- Phase 2: admin catalogue and immutable special-variant price snapshots.
DELIMITER //
DROP PROCEDURE IF EXISTS sp_case_opening_special_variant_rules_get//
CREATE PROCEDURE sp_case_opening_special_variant_rules_get() BEGIN SELECT r.RuleId,r.SourceItemId,r.Name,r.Tier,r.Description,r.PaintIndex,r.Phase,r.PatternSeed,r.MinimumFloat,r.MaximumFloat,r.RequiresStatTrak,p.PriceSnapshotId,p.Price FROM CaseOpeningSpecialVariantRules r LEFT JOIN (SELECT p.RuleId,p.PriceSnapshotId,p.Price FROM CaseOpeningSpecialVariantSnapshotPrices p INNER JOIN CaseOpeningSpecialVariantPriceSnapshots s ON s.PriceSnapshotId=p.PriceSnapshotId WHERE s.IsActive=1) p ON p.RuleId=r.RuleId ORDER BY r.IsActive DESC,r.SourceItemId,r.Name; END//
DROP PROCEDURE IF EXISTS sp_case_opening_special_variant_rule_save//
CREATE PROCEDURE sp_case_opening_special_variant_rule_save(IN p_rule_id CHAR(36),IN p_source_item_id VARCHAR(160),IN p_name VARCHAR(160),IN p_tier VARCHAR(40),IN p_description VARCHAR(500),IN p_paint_index VARCHAR(20),IN p_phase VARCHAR(50),IN p_pattern_seed INT,IN p_minimum_float DECIMAL(9,6),IN p_maximum_float DECIMAL(9,6),IN p_requires_stat_trak TINYINT(1),IN p_is_active TINYINT(1)) BEGIN INSERT INTO CaseOpeningSpecialVariantRules(RuleId,SourceItemId,Name,Tier,Description,PaintIndex,Phase,PatternSeed,MinimumFloat,MaximumFloat,RequiresStatTrak,IsActive,CreatedUtc,UpdatedUtc) VALUES(p_rule_id,p_source_item_id,p_name,p_tier,p_description,NULLIF(p_paint_index,''),NULLIF(p_phase,''),p_pattern_seed,p_minimum_float,p_maximum_float,p_requires_stat_trak,IF(p_is_active<>0,1,0),UTC_TIMESTAMP(6),UTC_TIMESTAMP(6)) ON DUPLICATE KEY UPDATE SourceItemId=VALUES(SourceItemId),Name=VALUES(Name),Tier=VALUES(Tier),Description=VALUES(Description),PaintIndex=VALUES(PaintIndex),Phase=VALUES(Phase),PatternSeed=VALUES(PatternSeed),MinimumFloat=VALUES(MinimumFloat),MaximumFloat=VALUES(MaximumFloat),RequiresStatTrak=VALUES(RequiresStatTrak),IsActive=VALUES(IsActive),UpdatedUtc=UTC_TIMESTAMP(6); END//
DROP PROCEDURE IF EXISTS sp_case_opening_special_variant_price_snapshots_get//
CREATE PROCEDURE sp_case_opening_special_variant_price_snapshots_get() BEGIN SELECT PriceSnapshotId,Name,Source,IsActive,ImportedUtc FROM CaseOpeningSpecialVariantPriceSnapshots ORDER BY ImportedUtc DESC,PriceSnapshotId DESC; END//
DROP PROCEDURE IF EXISTS sp_case_opening_special_variant_price_snapshot_create//
CREATE PROCEDURE sp_case_opening_special_variant_price_snapshot_create(IN p_snapshot_id CHAR(36),IN p_name VARCHAR(160),IN p_source VARCHAR(160),IN p_prices JSON) BEGIN INSERT INTO CaseOpeningSpecialVariantPriceSnapshots(PriceSnapshotId,Name,Source,Currency,IsActive,ImportedUtc) VALUES(p_snapshot_id,p_name,p_source,'GBP',0,UTC_TIMESTAMP(6)); INSERT INTO CaseOpeningSpecialVariantSnapshotPrices(PriceSnapshotId,RuleId,Price) SELECT p_snapshot_id,x.RuleId,x.Price FROM JSON_TABLE(p_prices,'$[*]' COLUMNS(RuleId CHAR(36) PATH '$.ruleId',Price DECIMAL(14,2) PATH '$.price')) x INNER JOIN CaseOpeningSpecialVariantRules r ON r.RuleId=x.RuleId; END//
DROP PROCEDURE IF EXISTS sp_case_opening_special_variant_price_snapshot_activate//
CREATE PROCEDURE sp_case_opening_special_variant_price_snapshot_activate(IN p_snapshot_id CHAR(36)) BEGIN IF NOT EXISTS(SELECT 1 FROM CaseOpeningSpecialVariantPriceSnapshots WHERE PriceSnapshotId=p_snapshot_id) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='The special-variant price snapshot could not be found.'; END IF; UPDATE CaseOpeningSpecialVariantPriceSnapshots SET IsActive=0 WHERE IsActive=1; UPDATE CaseOpeningSpecialVariantPriceSnapshots SET IsActive=1 WHERE PriceSnapshotId=p_snapshot_id; END//
DELIMITER ;
