<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>PersonalTools-4d9f2a76-6d94-4c6a-9c9f-4d8d6da9f927</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Gera.Chess" Version="1.2.0" />
    <PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
    <PackageReference Include="MySqlConnector" Version="2.4.0" />
    <PackageReference Include="Mapster" Version="7.4.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\CSMatches\" />
    <Folder Include="wwwroot\images\cs\maps\" />
    <Folder Include="wwwroot\images\cs\teams\" />
  </ItemGroup>

</Project>
